[project]
name = "kubernetescontextualist"
version = "1.2.4"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "kubernetes-asyncio>=34.3.3",
    "mcp[cli]>=1.25.0",
    "pydantic>=2.12.5",
    "structlog>=24.1.0",
]
