apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mcp-log-reader-clusterbinding
subjects:
  - kind: ServiceAccount
    name: mcp-log-reader
    namespace: default
roleRef:
  kind: ClusterRole
  name: mcp-log-reader-clusterrole
  apiGroup: rbac.authorization.k8s.io
